# Generated by Django 4.2.23 on 2025-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
